[project]
name = ""
version = ""
description = ""
authors = [
    {name = "WindKunai", email = "117094794+WindKunai@users.noreply.github.com"},
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

